### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by valterbarreira** [YunoHost-Apps/prestashop_ynh#21]
- Hardware: *VPS bought online 
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 
 
When uploading a theme file of 8,7 mb, it gives the error 413 Request Entity Too Large.

My server setting on prestashop:

Server info: Linux #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64
Server software version: nginx/1.14.2
PHP version: 7.3.33-1+0~20211119.91+debian10~1.gbp618351
Memory limit: 128M
Max execution time: 600
Max file upload limit: 1G

**Comment by ericgaspar** [comment]
Do you still have the same issue with the last version?

**Comment by valterbarreira** [comment]
Meanwhile because of the php 8 update, prestashop wasn't working and i uninstalled. I'll try again with the latest version
