### ISSUE TITLE
Prestashop_ynh uses incorrect PHP version

### ISSUE THREAD

**Issue by Bugsbane** [YunoHost-Apps/prestashop_ynh#24]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

I am on the testing version of Yunohost, which currently has PHP 7.4 and PHP 8.0.20 available. Prestashop installs without any errors, however upon going to open it, the only thing that displays on the frontend is:
"You need at most PHP 7.4 to install PrestaShop. Your current PHP version is 8.0.20"

For the record again, PHP 7.4 *is* installed, so it seems that prestashop_ynh is somehow using the wrong version of PHP by default (8.0.20)

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.0.7+202206212145 (unstable)
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *just running the unstable testing version. No other tweaks.*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- Installed Prestashop from the WebUI
- Added LetsEncrypt cert from the CLI
- Visit the domain homepage for my PrestaShop install

### Expected behavior

Prestashop homepage shows up, instead of an error about the PHP version.

### Logs

No errors show up in Yunohosts logs.

**Comment by cruftex** [comment]
Same problem here.
Version: 11.0.9.14 (stable)
Text when accessing the Prestashop URL after a fresh install:
You need at most PHP 7.4 to install PrestaShop. Your current PHP version is 8.0.22

**Comment by fedwiiix** [comment]
Same problem.
When the correctif ?

**Comment by fedwiiix** [comment]
Hey, Come On !

**Comment by ultrajej** [comment]
Same issue for me too!

**Comment by ericgaspar** [comment]
#26 should fix the issue

**Comment by valterbarreira** [comment]
It still gives this php error

**Comment by fedwiiix** [comment]
it's work now, thanks
